# Generated by Django 5.2.3 on 2025-07-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messageimage_alter_chatroom_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='chat.messageimage'),
        ),
    ]
