# Generated by Django 5.2.3 on 2025-07-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='images',
        ),
        migrations.AddField(
            model_name='message',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='chat/'),
        ),
    ]
