# Generated by Django 5.2.3 on 2025-07-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_images_message_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='id',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
