# Generated by Django 5.2.3 on 2025-06-23 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='full name')),
                ('role', models.CharField(choices=[('Parent', 'Parent'), ('Admin', 'Admin')], default='Parent', max_length=20, verbose_name='role')),
                ('subscription_plan', models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium')], default='Basic', max_length=10, verbose_name='subscription plan')),
                ('plan_expired_date', models.DateField(default='2050-01-01', verbose_name='Plan Expired')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='profile picture')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='contact number')),
                ('total_rides', models.PositiveIntegerField(default=0, verbose_name='total rides')),
                ('otp', models.PositiveIntegerField(blank=True, null=True, verbose_name='OTP')),
                ('otp_expired', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='active status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserPickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location_lat', models.CharField(default=0, max_length=100)),
                ('pickup_location_lng', models.CharField(default=0, max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
