# Generated by Django 5.2.3 on 2025-06-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpickuplocation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
