# Generated by Django 5.2.3 on 2025-06-19 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userpickuplocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpickuplocation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_location', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
