# Generated by Django 5.2.3 on 2025-06-19 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userpickuplocation_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Children',
        ),
    ]
