# Generated by Django 5.2.3 on 2025-06-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_expired_date',
            field=models.DateField(default='2050-01-01', verbose_name='Plan Expired'),
        ),
    ]
