# Generated by Django 5.2.3 on 2025-06-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_plan_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
