# Generated by Django 5.2.3 on 2025-06-23 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='color')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='vehicle type')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_model', models.CharField(max_length=200, verbose_name='make and model')),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Black', 'Black'), ('White', 'White'), ('Yellow', 'Yellow'), ('Brown', 'Brown'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Gold', 'Gold'), ('Beige', 'Beige'), ('Maroon', 'Maroon')], max_length=20, verbose_name='color')),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Van', 'Van')], max_length=20, verbose_name='vehicle type')),
                ('seats', models.PositiveIntegerField(verbose_name='seating capacity')),
                ('license_plate', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='license plate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
