# Generated by Django 5.2.3 on 2025-06-23 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='pool name')),
                ('departure_location', models.CharField(max_length=255, verbose_name='departure location')),
                ('arrival_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='arrival location')),
                ('repeat_type', models.CharField(choices=[('DoNotRepeat', 'Do not repeat'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Custom', 'Custom')], default='DoNotRepeat', max_length=20, verbose_name='repeat type')),
                ('scheduled_days', models.CharField(blank=True, max_length=255, null=True, verbose_name='scheduled days')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('is_return_trip', models.BooleanField(default=False, verbose_name='return trip')),
                ('return_time', models.TimeField(blank=True, null=True, verbose_name='return time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools_created', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pools', to='vehicle.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PoolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Member', 'Member'), ('Driver', 'Driver'), ('Admin', 'Admin')], default='Member', max_length=10, verbose_name='role')),
                ('pickup_location_lat', models.CharField(default='0', max_length=500)),
                ('pickup_location_lng', models.CharField(default='0', max_length=500)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Leave', 'Leave')], default='Pending', max_length=10, verbose_name='status')),
                ('driving_days', models.CharField(blank=True, max_length=255, null=True, verbose_name='driving days')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('children', models.ManyToManyField(blank=True, related_name='pool_members', to='children.children')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pool.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pool', 'user')},
            },
        ),
    ]
