# Generated by Django 5.2.3 on 2025-06-19 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='pool name')),
                ('departure_location', models.CharField(max_length=255, verbose_name='departure location')),
                ('arrival_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='arrival location')),
                ('repeat_type', models.CharField(choices=[('DoNotRepeat', 'Do not repeat'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Custom', 'Custom')], default='DoNotRepeat', max_length=20, verbose_name='repeat type')),
                ('scheduled_days', models.CharField(blank=True, max_length=255, null=True, verbose_name='scheduled days')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('is_return_trip', models.BooleanField(default=False, verbose_name='return trip')),
                ('return_time', models.TimeField(blank=True, null=True, verbose_name='return time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools_created', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pools', to='vehicle.vehicle')),
            ],
        ),
    ]
