# Generated by Django 5.2.3 on 2025-06-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolmember',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Decline', 'Decline'), ('Leave', 'Leave')], default='Pending', max_length=10, verbose_name='status'),
        ),
    ]
