# Generated by Django 5.2.3 on 2025-06-19 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        ('pool', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Member', 'Member'), ('Driver', 'Driver'), ('Admin', 'Admin')], default='Member', max_length=10, verbose_name='role')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Leave', 'Leave')], default='Pending', max_length=10, verbose_name='status')),
                ('driving_days', models.CharField(blank=True, max_length=255, null=True, verbose_name='driving days')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('children', models.ManyToManyField(blank=True, related_name='pool_members', to='children.children')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pool.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pool', 'user')},
            },
        ),
    ]
