# Generated by Django 5.2.3 on 2025-06-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_alter_poolmember_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Active', max_length=20, verbose_name='status'),
        ),
    ]
