# Generated by Django 5.2.3 on 2025-06-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_poolmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolmember',
            name='pickup_location',
            field=models.CharField(default='', max_length=500),
        ),
    ]
